### ISSUE TITLE
Non Standalone Multiple Publisher Persistance

### ISSUE THREAD

**Issue by rudijs** [rudijs/amqp.node-rpc-factory#3]
@robraux Hi Rob,

I've noticed a problem with allowing multiple instances of publishers to exist.

I'm using KoaJS (next gen of ExpressJS) and if the consumer is down when the publisher (the webserver) tries to send a message it will create a new persistent connection for every attempt.

For example, the consumer is down, and the web server sends 10 messages, it will create 10 (persistant) connections.

What it needs to do in my case is have 10 failures on the same single connection.

I'm going to dig into this more. 

What you've pointed out here in you pull request:

```
The problem was with Object.create, the resulting object sets a property of a property. 
When two instances are created, they shared the same properties (e.g. queue, url, etc.).
```

This is actually the behavior I need when the publisher is a web server.

Can you elaborate more why you need the publisher to have multiple instances?

Thanks.

**Comment by rudijs** [comment]
OK, I think there's a couple things going on here.

First up, the issue I've had is related to reseting the connection on time out.

The fix for that will be:

```
 // Reset the connection
 if(err.message != 'RPC Reply Timeout') {
    this.connection = null;
}
```

Even though there's no conusmer the connection to RabbitMQ is OK and can be reused.

Setting this.connection to null without closing it leads to the many open unused persistant connections.

They cannot be autoDelete'd as they have a connection - the webserver.

Second issue I've found is handling uncaught exceptions with crash the web server.

For example, KoaJS is connected then RabbitMQ goes down.

This is how the domain properly handles the excpetion **without** crashing the web server:

```
Publisher: Unexpected amqplib connection error handled by domain:Error: Unexpected close
    at succeed (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:265:13)
    at onOpenOk (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:247:5)
    at /media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:160:32
    at /media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:154:12
    at Socket.recv (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:486:12)
    at Socket.g (events.js:257:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:163:7)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:402:7)
```

The problem currently now with multple instances of the publisher is the expection is not caught properly:

```
Publisher: Unexpected amqplib connection error handled by domain:Error: Unexpected close
    at succeed (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:265:13)
    at onOpenOk (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:247:5)
    at /media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:160:32
    at /media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:154:12
    at Socket.recv (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:486:12)
    at Socket.g (events.js:257:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:163:7)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:402:7)
domain.js:172
  ee.domain = null;
            ^
TypeError: Cannot set property 'domain' of null
    at Domain.remove (domain.js:172:13)
    at Object.<anonymous> (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqp-rpc-factory/lib/rpc-publisher-factory.js:48:28)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:166:7)
    at ChannelModel.emit (events.js:139:14)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:166:7)
    at Connection.C.onSocketError (/media/rudi/crypt2/projects/ride-share-market-api/node_modules/amqplib/lib/connection.js:346:10)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:163:7)
```

It looks like multiple instances of the publisher when used by a server (KoaJS or ExpressJS) is the cause of this.

**Comment by rudijs** [comment]
Hrm .. Actually .. I think the fix for all the above is just

```
    // Reset the connection
    if(err.message != 'RPC Reply Timeout') {
      this.connection = null;
      this.currentConnection = null;
    }
```

I think this is also the proper fix for the closed issue 'Empty Idle Queues'.

I have a feeling those Empty Idle Queues were also the result of consumer not listening when the publisher is used in non-standalone mode.

I'll follow up more tomorrow.

**Comment by rudijs** [comment]
Fixed and published here: https://github.com/rudijs/amqp.node-rpc-factory/commit/20a1e172791a0dc3918d116a32c9a87f84d244bc

**Comment by robraux** [comment]
@rudijs -- sorry for the delayed reply, which I could have commented sooner. To answer your question, I have the need for multiple publishers because the RPC is utilized for two distinct things. The API is publishing on two different RPC queues, depending on the nature of the request. 

The reason for this, is that one request is expected to be a bit slower response time (think generating reports, etc), whereas the other must be as quick as possible. 

It looks like you've solved the issue regarding the multiple queues sufficiently, but I'm happy to provide any more feedback, or provide additional PR's if you see additional gaps.
