### ISSUE TITLE
Publisher: IllegalOperationError: Connection closed

### ISSUE THREAD

**Issue by PuKoren** [rudijs/amqp.node-rpc-factory#6]
Hello,

When I send messages to the consumers, I have this error triggered once every two request.

Stack trace:

``` js
Publisher: Publishing: 
Publisher: IllegalOperationError: Connection closed
    at Connection.<anonymous> (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/lib/connection.js:354:11)
    at Channel.C.sendImmediately (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/lib/channel.js:63:26)
    at Channel.C.sendOrEnqueue (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/lib/channel.js:74:10)
    at Channel.C._rpc (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/lib/channel.js:130:8)
    at Channel.C.rpc (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/lib/channel_model.js:59:8)
    at /home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/lib/channel_model.js:70:17
    at tryCatchReject (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/home/koren/dev/dialonce/amqp-tests/node_modules/amqp-rpc-factory/node_modules/amqplib/node_modules/when/lib/makePromise.js:590:4)
```

Do you know where it could come from ?

**Comment by PuKoren** [comment]
This was because I had `standalone` set to true in my queue config. Sorry about that!
